### ISSUE TITLE
Pull request analysis error: "No such branch/commit found"

### ISSUE THREAD

**Issue by vasily-v-ryabov** [quantifiedcode/issues#10]
Recent pull request seems not analysed: https://www.quantifiedcode.com/app/project/gh:pywinauto:pywinauto?branch=__pull_request_58
Message `No such branch/commit found` is shown.

GitHub link: https://github.com/pywinauto/pywinauto/pull/58

**Comment by vogelsgesang** [comment]
We changed the way in which pull requests are presented some time ago. Pull requests are displayed in a separate views which only summarize the differences between old and newly introduced issues. For example, the pull request 58 can be found [here](https://www.quantifiedcode.com/app/project/gh:pywinauto:pywinauto/diff/d2972e6dfea5925db9b66b3dddba60e5a29d3e5d/f89d93b1bccaa507521c23f2279963e5e5309ac0/issues?pr=58).

**Comment by vasily-v-ryabov** [comment]
Looks very nice! :+1:
