### ISSUE TITLE
Missing argument to super() inconsistent

### ISSUE THREAD

**Issue by NiklasRosenstein** [quantifiedcode/issues#11]
My project uses Python 3 where you don't need an argument to `super()`. QC doesn't complain for all cases but three (seemingly random) files. You can find the QC results [here](https://www.quantifiedcode.com/app/project/fcdfee657ce7446caed1141de62199af?severity=1&groups=code_patterns%3A1ICBjxCD%3Af2).

**Comment by ArnossArnossi** [comment]
Hi, sorry for the delay. We had to refactor our tagging system in order to fix this.
	If you reset your project and set the tag for python-3.x this issue should be fixed.

	To reset and reanalyze your project you can follow theses steps:
	   1. Open your project's settings
	   2. Click on "Danger Zone" -> "Reset project"
	   3. Wait some time until we reanalyzed your project

**Comment by programmdesign** [comment]
Considered closed. Re-open if the issue persists.
