### ISSUE TITLE
Viewing issues doesn't work on branches other than master

### ISSUE THREAD

**Issue by benjaminjkraft** [quantifiedcode/issues#12]
See for example https://www.quantifiedcode.com/app/project/8943480ec8a24f28ae041c720d8e0874?branch=origin%2Fmain; if you click on the issue detail buttons, they don't work, and you'll see 404s in the console (and the requests that are 404ing are clearly not specifying a branch name).  This is because the repository doesn't have a `master` branch (for historical reasons we use `main` instead); on repositories with a `master` branch, the issue detail buttons will work, but will show information for `master` rather than the selected branch.

**Comment by vogelsgesang** [comment]
Thanks for reporting this issue.

We have fixed it in our development branch and viewing issues on the non-`master`-branch will be working as expected after the next deployment. I am closing this ticket for now and I will ping you as soon as the changes are online.
