### ISSUE TITLE
NotImplemented exception

### ISSUE THREAD

**Issue by drnextgis** [quantifiedcode/issues#14]
I'm using `NotImplemented` constant within `__eq__` method of my class but get:

```
`NotImplemented` raised, instead of `NotImplementedError`
```

**Comment by ArnossArnossi** [comment]
Hi, sorry for the delay. We fixed this issue, thanks for pointing it out. If you reset your project the code check should work as expected now.

To reset and reanalyze your project you can follow theses steps:

1.  Open your project's settings
2.  Click on "Danger Zone" -> "Reset project"
3.  Wait some time until we reanalyzed your project

**Comment by drnextgis** [comment]
Thanks! Now it works fine.
