### ISSUE TITLE
Queue not progressing?

### ISSUE THREAD

**Issue by CarstVaartjes** [quantifiedcode/issues#16]
Hi,

it seems that the queues for my projects are frozen/broken, it has stayed like this for over 12 hours now: "Project queued for analysis: You're at position 65."

BR Cart

**Comment by programmdesign** [comment]
Hi Cart. Thanks for reporting. Just gave the analysis queue more power. Your analysis should be done in a bit.

**Comment by CarstVaartjes** [comment]
thanks!
