### ISSUE TITLE
Is badge supported for private repositories ? 

### ISSUE THREAD

**Issue by msjaiswal** [quantifiedcode/issues#17]
Hello, 
I used the markdown on the README page but it shows broken image. My guess is that it might be some authentication problem since it is a private repository. Can you tell me if it is supported ? 

Thanks.

**Comment by programmdesign** [comment]
Hi @msjaiswal. I'll look into this. Right now, the badge indeed works only for public repos.

**Comment by msjaiswal** [comment]
Ok thanks.

**Comment by programmdesign** [comment]
Hi @msjaiswal. The badge should now work. Can you confirm?

**Comment by msjaiswal** [comment]
Yes, it works now. Thank you.
