### ISSUE TITLE
.checkignore seems to be ignored

### ISSUE THREAD

**Issue by alan-unravel** [quantifiedcode/issues#23]
I have a .checkignore set to ignore all files in  my projects migration directories, yet it is still checking these directories! Any insight into this issue would be great.

**Comment by programmdesign** [comment]
@alan-unravel can you please post your .checkignore file here or send me the link to your repo?

**Comment by alan-unravel** [comment]
Yeah sure, I can't post a link since it is a private repo but here is the .checkignore(with some app names changed):
```
app1/migrations/*
app2/migrations/*
functional_tests/migrations/*
```

Let me know if I have done something wrong, thanks!

**Comment by programmdesign** [comment]
Looks fine actually. Did you re-analyze your project? What does the log say? Can you please post it here or send it to me using the contact form https://www.quantifiedcode.com/contact

**Comment by alan-unravel** [comment]
Seems like a re-analyze is what is needed, will let you know how it goes!

**Comment by programmdesign** [comment]
:+1:

**Comment by alan-unravel** [comment]
Just a quick question does, the .checkignore have to be in the master branch? We have two tracked and only one has the .checkignore. And a follow up is, does the .checkignore of an incoming PR get checked?

**Comment by programmdesign** [comment]
For now, we only consider the .checkignore in your master branch.

**Comment by alan-unravel** [comment]
Okay, thanks!
