### ISSUE TITLE
Code style recommendations block github from merge if Quantified code is required to pass

### ISSUE THREAD

**Issue by alan-unravel** [quantifiedcode/issues#25]
Seems odd that recommendations block, is there a way for us to exclude certain types of styles recommendations?

**Comment by programmdesign** [comment]
Yes. In your project settings you can turn all checks on or off.

Christoph

Von meinem iPhone gesendet

On 18.11.2015, at 17:40, alan-unravel <notifications@github.com<mailto:notifications@github.com>> wrote:


Seems odd that recommendations block, is there a way for us to exclude certain types of styles recommendations?

-

**Comment by alan-unravel** [comment]
Great thanks
