### ISSUE TITLE
Avoid accessing protected class members from outside

### ISSUE THREAD

**Issue by jjgreen** [quantifiedcode/issues#27]
A laudable aim, but I think I get false positives for the two recursive calls in the following code 

```
def _binary_pow(self, n) :
        """
        Integer power implemented by binary division.
        """
        p = self
        if n == 1 :
            return p
        if n % 2 == 0 :
            p = p._binary_pow(n / 2)
            return p * p
        else :
            return p * p._binary_pow(n - 1)
```

**Comment by programmdesign** [comment]
Thanks for pointing this out. We'll have a look. If you like, you can change any code check yourself. Wanna give it a try? http://docs.quantifiedcode.com/patterns/language/index.html

**Comment by TonyFlury** [comment]
Also confirmed when an instance method accesses a class attribute which starts with a "_". I think the definition of outside needs some work :-)

**Comment by adewes** [comment]
We'll work on improving this check, right now our engine still has some trouble understanding recursive assignments like the one you're showing, as it requires quite deep data flow analysis.

**Comment by TonyFlury** [comment]
The issue I have isn't recurrsion - although the OP's issue definitely is. Should I raise another issue for my related by different problem ?
