### ISSUE TITLE
I've clicked "Fix automatically!" a few times throughout the day, but I haven't yet gotten any pull requests

### ISSUE THREAD

**Issue by dwiel** [quantifiedcode/issues#28]

**Comment by programmdesign** [comment]
We are looking into this.

**Comment by programmdesign** [comment]
@dwiel Can you try again, after you granted us access for private repositories? If you just gave access to public repos, GitHub access rights don't allow us to open a Pull Request.

**Comment by adewes** [comment]
@dwiel please try again, we have improved our permissions checks, so we will ask you to give us the required access before making a pull request.
