### ISSUE TITLE
"Unable to fix the issue due to network problems"

### ISSUE THREAD

**Issue by dwiel** [quantifiedcode/issues#29]
I click Fix automatically, the "sure, fix it" in the modal, then I get this pop up: "Unable to fix the issue due to network problems".  It seems to be from the following failed request:

`POST https://www.quantifiedcode.com/api/v1/project/undefined/autofix/code_patterns:4ACGxFj1 404 (NOT FOUND)`

**Comment by programmdesign** [comment]
@dwiel Should be fixed. Try again please.

**Comment by dwiel** [comment]
works now, thanks
