### ISSUE TITLE
Allow unused arguments if named "_"

### ISSUE THREAD

**Issue by jjgreen** [quantifiedcode/issues#30]
There are several cases where I'd like a function to have different implementations but the same signature, for example
```
    if verbose :
        def info(fmt, *args) :
            sys.stdout.write(fmt % args)
    else :
        def info(_, *args) :
            pass
```
Could `Avoid unused arguments` not trigger when the unused variable is `_`?

**Comment by programmdesign** [comment]
Hi @jjgreen. Thanks. Do you think this is something we should have in the general pattern that applies to anyone or would you like to create an adapted version of the existing pattern (you can do this yourself if you like and share it back to the community by making it public).

**Comment by jjgreen** [comment]
I'd say this is a quite common idiom -- another example is a method implemented in a set of subclasses, one which is called in the base class; then one would want (or need) the same signature for the methods, even if some of them did not use all of the arguments (for example, the method `variables` in two subclasses  [here](https://github.com/jjgreen/mvpoly/blob/master/src/python/mvpoly/dict.py#L388) and [here](https://github.com/jjgreen/mvpoly/blob/master/src/python/mvpoly/cube.py#L357))

**Comment by jjgreen** [comment]
... which is not to say I'm unwilling to have a crack at making a modified version, but I'm having some problems in finding the source for the original, would you have a link to it?

**Comment by programmdesign** [comment]
Give it it a try. The original is here: https://www.quantifiedcode.com/app/issue_class/edf4ba30fdae4465b036abec666962af 

Click on the edit button "Pen"-Symbol. This lets you edit/access the actual Code pattern and the test cases behind.

Docs on the language: http://docs.quantifiedcode.com/patterns/language/index.html

**Comment by jjgreen** [comment]
For the life of me, I cannot see a pen on that page.  Could you mark it on the attached screenshot?

![screenshot from 2015-12-08 16 32 06](https://cloud.githubusercontent.com/assets/3464626/11661368/8b032bc0-9dc9-11e5-8417-71878705951e.png)

**Comment by programmdesign** [comment]
Hm, seems to be glitch on our side. Let me check.

**Comment by programmdesign** [comment]
Here's the pattern for the moment, if you'd like to just create a new code check:

$: {match_first: [args]}
node_type: functiondef
args:
  args:
  - $repeat: {$anything: {}}
  - node_type: name
    id:
      $and:
      # whitelist default arguments for methods
      - $not: {$or: [self, cls]}
      - name: data_var
        $store: {$anything: {}}
body:
  $not:
    $anywhere:
      node_type: name
      id: {$ref: {name: data_var}}

**Comment by jjgreen** [comment]
Added a (publicly available) check `Use an underscore for unused arguments`, just a 1-char modification to the above of course, I couldn't find how to format the documentation as python code though -- are there any docs/links to the markdown flavour used?

**Comment by jjgreen** [comment]
By the way, on creating my own check, the pen icon is as plain as the nose on my face :-)

**Comment by jjgreen** [comment]
Resolved

**Comment by programmdesign** [comment]
Nice job! I'll review the pattern and approve it as public check if nothing comes up :)
