### ISSUE TITLE
False positive in child class name as first argument to `super`

### ISSUE THREAD

**Issue by iMichka** [quantifiedcode/issues#31]
Hi

I think there are some false positives in some parts of my code. Please see the following 6 critical errors labelled as ```Use child class name as first argument to `super` call``` in this file:

https://www.quantifiedcode.com/app/project/117af14ef32a455fb7b3762e21083fb3/snapshot/8210d5a640bb4c12b4a89461bd5cd93a/file/pygccxml/declarations/matchers.py?severity=1

To me the code looks correct, and is also working (it is a project I inherited so I did not write this part of the code, so there may be errors. But these classes are covered by some tests so it should be OK).

**Comment by programmdesign** [comment]
Hi Michka, you are right. We already disabled this check. If you got to your project's setting and click re-analyze, the issue should no longer be raised.

On 08 Dec 2015, at 21:32, Michka Popoff <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi

I think there are some false positives in some parts of my code. Please see the following 6 critical errors labelled as Use child class name as first argument to `super` call in this file:

https://www.quantifiedcode.com/app/project/117af14ef32a455fb7b3762e21083fb3/snapshot/8210d5a640bb4c12b4a89461bd5cd93a/file/pygccxml/declarations/matchers.py?severity=1

To me the code looks correct, and is also working (it is a project I inherited so I did not write this part of the code, so there may be errors. But these classes are covered by some tests so it should be OK).

**Comment by iMichka** [comment]
Thanks, the error is now gone. Sorry for the long delay.
