### ISSUE TITLE
Pull request status not updated and comments not made

### ISSUE THREAD

**Issue by tomato42** [quantifiedcode/issues#32]
I have a pull request: https://github.com/tomato42/tlslite-ng/pull/68 and while the analysis on it was run: https://www.quantifiedcode.com/app/project/59e6019ef3c84ad7ba30c49ec46d990f/diff/6a78b977a4785239f3f006c79d8aefabc12ee637/ed21efcdff22b0d50ffeae447101d6522769d221/issues?pr=68  it has not updated the pull request status or filed a comment, despite both settings being on in the project's config.

**Comment by programmdesign** [comment]
@adewes can you please look into this?

**Comment by tomato42** [comment]
few ideas (based on other hooks problems): 
 * It's a fork not a "base" repo
 * It's a PR to a fork
 * it's an updated (re-pushed/re-based) pull request

**Comment by adewes** [comment]
I just reset the project to have it re-analyzed, I'll also check your Github permissions.

**Comment by adewes** [comment]
So it seems that we don't have the required access rights. To fix the problem, please do the following:

* Go to your settings
* Open the "Linked accounts" tab
* Click on "revoke Github access" and afterwards on "Connect" again

You will be redirected to Github and will have to acknowledge the changed permissions, afterwards your project should get correctly analyzed. To do a full re-analysis, please go to the project settings, open the "Danger Zone" tab and click on "Reset Project". After the re-analysis the pull request status should show up on Github.

**Comment by tomato42** [comment]
Hmm, when I did the authorization (after revoking the access) I got the following:
```
Public data only
Limited access to your public data

This application will be able to identify you and read public information. 
```

after logging in I did get
```
It seems that you haven' provided us with the
necessary access rights to your Github account.
Please try signing up again.
```

and then it did ask for "Repository webhooks and services" and "Repositories" permissions on top of the "Public data only"

**Comment by programmdesign** [comment]
We'll look into this asap.

**Comment by programmdesign** [comment]
@tomato42 seems your PRs have a status update now. Can you confirm all works for you?

**Comment by tomato42** [comment]
just waiting for a colleague to submit PR to see if it works with 3rd party pull requests too, will close it as soon as I confirm it (should be before tomorrow evening)

**Comment by tomato42** [comment]
looks fixed: https://github.com/tomato42/tlslite-ng/pull/82

Awesome! Thanks!
