### ISSUE TITLE
Bad variable naming on https://www.quantifiedcode.com/app/pattern/3P0qV6OB

### ISSUE THREAD

**Issue by zopyx** [quantifiedcode/issues#4]
The example code of this pattern uses 'list' as a variable name. This is an anti-pattern by itself.
Never ever use Python build-in types as variable names...should be renamed to 'some_list' or something similar.

**Comment by zopyx** [comment]
The explicit check could be rewritten in a one-onliner as

list = list or []

**Comment by programmdesign** [comment]
Correct. Thanks. We'll fix it.

**Comment by ArnossArnossi** [comment]
Thanks for the info. I just fixed it.
