### ISSUE TITLE
"Missing required field in settings" Out of date for Django 1.9

### ISSUE THREAD

**Issue by danpalmer** [quantifiedcode/issues#40]
The check *Missing required field in settings* requires `TEMPLATE_DEBUG` to be defined. This is deprecated as of Django 1.8, and the correct usage is to define in the new `TEMPLATES` dictionary.

**Comment by programmdesign** [comment]
Thanks. Tagged the check accordingly: https://www.quantifiedcode.com/app/issue_class/17b87b406f664565ae1ce054d9586c67. 

If you like, you can go ahead an create a migration pattern to show the migration path. We already have some of them for other settings: https://www.quantifiedcode.com/app/issue_class/6f1b0d6580e04149983617cefa39d08c
