### ISSUE TITLE
"The page you are trying to access cannot be loaded." when opening issues

### ISSUE THREAD

**Issue by spaceisstrange** [quantifiedcode/issues#45]
Hi, I've been having this problem for a few days now. Basically I cannot open any issue not from my projects nor from projects of other people.

<img width="870" alt="captura de pantalla 2016-02-14 a las 21 53 16" src="https://cloud.githubusercontent.com/assets/6024783/13036352/71306b8c-d365-11e5-9eb4-af4d3d63a7a1.png">

I tried it in Safari and Chrome and both have the same problem. Is there an issue with the web or is it mine?

Thanks for this wonderful project!

**Comment by adewes** [comment]
Hey @spaceisstrange , sorry for the inconvenience! Can you tell us which project it is you're having trouble viewing? You can send me the link to andreas@quantifiedcode.com if you don't want to post it publicy.

**Comment by spaceisstrange** [comment]
Hi @adewes, as I said it happens with pretty much every project I tried. But I started noticing it in my personal one:

**Comment by spaceisstrange** [comment]
Okay, it seems like the issue is gone and now I can load everything just fine! It takes a long time, though, but at least it loads.

**Comment by adewes** [comment]
Good to hear that @spaceisstrange , the queries are indeed very slow, I'll look into this!
