### ISSUE TITLE
Badges for specific branch

### ISSUE THREAD

**Issue by iMichka** [quantifiedcode/issues#5]
Hi

I wanted to know if there is a possibility to get badges for a specific branch? It seems that the badge is only generated for the master branch. That would be great, as I mainly work on a "develop" branch, and my master branch is used as a release branch.

**Comment by adewes** [comment]
Hey @iMichka , thanks for your message!

This is possible (but undocumented right now), just use the following format for the badge URL:

https://www.quantifiedcode.com/api/v1/project/[your-project-id]/snapshot/origin/[your-branch-name]:HEAD/badge.svg

For example, if I wanted to display the badge for the **corentin/master** branch of my BlitzDB project, I would use the following image URL:

https://www.quantifiedcode.com/api/v1/project/gh:adewes:blitzdb/snapshot/origin/corentin/master:HEAD/badge.svg

Hope this answers your question, if not feel free to write again!

**Comment by iMichka** [comment]
Great, that worked. Exactly what I need.

I guess an entry in the FAQ would be great, or an option to chose between branches for the badges.

Thanks for the help.

**Comment by iMichka** [comment]
Hi; it seems that this is no more working (probably since some weeks already). Here an example on my project:
https://github.com/gccxml/pygccxml

Has the URL changed ?

**Comment by vogelsgesang** [comment]
Yes, the URL changed. The badge for your branch is now available under https://www.quantifiedcode.com/api/v1/project/117af14ef32a455fb7b3762e21083fb3/snapshot/origin:develop:HEAD/badge.svg.
