### ISSUE TITLE
Stuck on "Analysis in progress"

### ISSUE THREAD

**Issue by CarstVaartjes** [quantifiedcode/issues#52]
Hi,

for visualfabriq/api the quantifiedcode checks have become stuck since 2 weeks on "Analysis in progress". Could you please check what's going wrong?

BR

Carst

**Comment by adewes** [comment]
Hi Carst,

thanks for reporting this, I'll check it immediately, will have a solution until the end of the day. We're currently migrating our analysis routines to a new engine (which is significantly faster), so it can come to problems for individual projects, sorry for the inconvenience.

I'll get back to you as soon as I have a fix.

Best
Andreas

**Comment by CarstVaartjes** [comment]
Thanks Andreas!!

**Comment by adewes** [comment]
It should work again @CarstVaartjes . There was a very large Python file it seems that was too much for our algorithms, thanks for pointing us to this issue :)

We are working to implement better monitoring to detect such issues automatically in the future, sorry again for the inconvenience.

**Comment by CarstVaartjes** [comment]
Thanks!! works great again :)
