### ISSUE TITLE
Monitor issues for a subset of files/directories

### ISSUE THREAD

**Issue by jdm** [quantifiedcode/issues#53]
https://github.com/servo/servo/ contains vendored versions of a number of upstream python-based repositories. We would be interested in monitoring our own, original python code for the issues that get reported, but it's less useful to us to see the reports on code that we don't maintain.

**Comment by adewes** [comment]
Hey @jdm, you can do this by adding a .checkignore file to your repository:

http://docs.quantifiedcode.com/configuration/config_checkignore.html

After adding the file you might need to reset your project for all changes to take effect.

Does this solve your problem?

**Comment by jdm** [comment]
Sounds like it!
