### ISSUE TITLE
The Future of QuantifiedCode

### ISSUE THREAD

**Issue by enlite93** [quantifiedcode/issues#62]
What happened?

**Comment by enlite93** [comment]
Thank you for your service :+1:

**Comment by CarstVaartjes** [comment]
I also asked for some clarification on twitter, but there's no response at all unfortunately. On linkedin you can see one of co-founders left a while back... :/
Really liked it, so for me it's a shame. For a paid service, I would like at least a bit more explanation, suggestions for alternatives for its users etc...

**Comment by enlite93** [comment]
Possible alternatives I've not tried yet

 * https://landscape.io

**Comment by adewes** [comment]
Hey, thanks for reaching out! I will be sending out information regarding the shutdown. Basically it's just not profitable as there is not enough revenue coming in through the site that justifies the investment in time.

I have been working on an OS version of the site, if I can find people to contribute to that I'll publish it after shutting down the main service, so you'll be able to host it yourself.

**Comment by adewes** [comment]
Thanks in any case @CarstVaartjes for being one of our earliest and most loyal customers, please don't hesitate to reach out if I can help you to find an alternative to our service (same for you @enlite93).

**Comment by CarstVaartjes** [comment]
Hi @adewes, 

I can perfectly understand the reason (my complaint was mostly that it was a bit sudden and without any further explanation). I know you guys have put a *lot* of effort in it and I really liked it so i'm sad to see it go. I hope the best for all of you.
An OS version would be great as I think that some of the elements were really better than other solutions out there (and the ability to hook into git was very nice too). Let me know what kind of help you require and we might be able to help you?

BR Carst

**Comment by adewes** [comment]
We can possibly extend the shutdown period by a month or two to make the transition easier.

I worked on an initial OS version of checkmate (the tool we use in the backend) and the frontend + API, which is in a good state already. I'm looking for contributors and testers, if you're interested in either one just let me know, will contact you as soon as we're moving ahead with this then.

**Comment by itsthejoker** [comment]
I'm down for testing a self-hosted version if you still need people. Thanks for the service; I recommended it a lot.

**Comment by CarstVaartjes** [comment]
Hi, 

extending it would be nice but if it runs you into a lot of additional costs, i would not want to do that to you. We're definitely interested in testing any OS version and will contribute if needed (resources are tad constraint so it would be some evening hours stuff from me ;)

**Comment by ismailsunni** [comment]
Ouch, I find this great tool in the extended period...

Anyway, it's a cool tool.

**Comment by peterjc** [comment]
I'm grateful that is has continued as long as it has, but I realise that October 2016 has passed and we're into 2017 now - is QuantifiedCode still expecting to shut down @adewes? There is no obvious mention of this on the main webpage.

**Comment by adewes** [comment]
Hey @peterjc , thanks for your message!

The service will keep running for now and I will release an OS version soon, probably in February (it's already finished but I need to clarify a few formal things before releasing it).

Hence you should be able to use the online service for longer and soon you will have the possibility to install a local version of QuantifiedCode on your own infrastructure.

In any case I will not shut down the service without any prior announcement!

**Comment by peterjc** [comment]
That's great news. Maybe close this issue, or at least re-title it? Thanks!

**Comment by adewes** [comment]
Done!
