### ISSUE TITLE
Lines using reverse() trigger "Use reverse() instead of hard-coded URL" error

### ISSUE THREAD

**Issue by mathuin** [quantifiedcode/issues#67]
I have a Django app with the following method on one of its models:

```
def get_absolute_url(self):
    return reverse('meadery_product', kwargs={'product_slug': self.slug})
```

This code triggers the error "Use reverse() instead of hard-coded URL".

Also, the error message has some typos in it:

"Try to use revers() instead of hard-coding the url to ensure it is correctly set and valid."

Should be reverse() and URL.

**Comment by adewes** [comment]
Thanks for reporting this, it seems to be an error indeed, I fixed the pattern. Please reset your analysis to see the changes, and feel free to close this issue if you think the problem is resolved.

**Comment by mathuin** [comment]
Thank you for responding quickly!  The problem appears to be resolved.
