### ISSUE TITLE
changed Github username

### ISSUE THREAD

**Issue by robphoenix** [quantifiedcode/issues#68]
I've recently changed my Github username and now can't access my previous repos

> The project already exists and is owned by another user. Please ask your team members to grant you access to the project on QuantifiedCode.

**Comment by adewes** [comment]
Hey Rob, sorry to hear that. What was your previous Github username if I may ask?

**Comment by robphoenix** [comment]
no worries, bordeltabernacle

**Comment by adewes** [comment]
@robphoenix , I transferred ownership of the projects to your new Github account. You need to confirm this in your settings (tab "pending ownership transfers"). Please let me know if your run into any kind of problem.

**Comment by robphoenix** [comment]
Yes, that's worked, thankyou. Was this perhaps my fault in the first place, could I have revoked access on my old github username account and then re-added it?

**Comment by adewes** [comment]
Yes that would have been possible, though I would say it's never your fault, as we simply didn't take this into account when designing the system.

**Comment by robphoenix** [comment]
Well it's not a regular occurrence I imagine. Thanks for sorting this out so quickly. And thanks  for building this, I find it really useful and it's contributed to making me a better programmer for sure. 👍

**Comment by adewes** [comment]
Thanks @robphoenix , really appreciate your great feedback!
