### ISSUE TITLE
Analyze project selection only displays a subset of all repos

### ISSUE THREAD

**Issue by willingc** [quantifiedcode/issues#7]
When selecting a repo to analyze from the list of possible repos, https://www.quantifiedcode.com/app/project/new, only the first 100(?) are displayed. If a user has more repos, say 250, there should be a next page option to access those repos.

Overall, cool project :cake:

**Comment by programmdesign** [comment]
Hi @willingc. Glad you like it! :) Bug confirmed, we'll put it on the roadmap.

**Comment by jakirkham** [comment]
Would add that it doesn't show repos from organizations that user is a member of.

**Comment by vogelsgesang** [comment]
@willingc: we added pagination for the Github projects. You should be able to add all repositories now.

@jakirkham: Did you grant us access to your private repositories? Does the organization only have public repositories or private repositories as well?

**Comment by jakirkham** [comment]
Thanks for getting back to me, @vogelsgesang. I didn't grant permission for private repos. The organization that I was looking for has a mix of public and private repos.

**Comment by vogelsgesang** [comment]
For the time being you will have to grant us access to private repositories in order to access the repositories of your organizations.

Most likely we will add the possibility to access public repositories of organizations later. But currently this is not on our schedule.

**Comment by programmdesign** [comment]
@jakirkham: you can always add public repos via URL in the add project dialog.
