### ISSUE TITLE
Project Scheduled for Deletion, Cannot Add it back

### ISSUE THREAD

**Issue by mcrowson** [quantifiedcode/issues#70]
I cannot add a project. I get the message that it was scheduled for deletion and try back in a few minutes. That was 12 hours ago and I still get the same message.

https://github.com/mcrowson/flask-sessionstore

## Steps to Reproduce
Forked a project (flask-session)
Renamed the project (flask-sessionstore)
Renamed the project (flask-sessionstore-fork)
Created a new project with the name flask-sessionstore

In all of that I can easily see QC getting some wires crossed. Thanks for the patience and please let me know what I can do to fix this.

**Comment by adewes** [comment]
@mcrowson seems like our deletion queue had a little hiccup, it should work again! If it doesn't please let me know, will immediately look into it then.

**Comment by adewes** [comment]
Oh and please feel free to close this issue if you think the problem is resolved.

**Comment by mcrowson** [comment]
It allowed me to add it. And don't I know about queue issues :D
