### ISSUE TITLE
ENH: Add ability to turn off email notifications (and/or route notifications through something else)

### ISSUE THREAD

**Issue by jakirkham** [quantifiedcode/issues#9]
Personally, not a big fan of have my email boxed filled with notifications about builds and tests. It would be good if we could at a minimum turn this off. Also, if I do want the notifications, I normally wanted them routed in some other form so allowing a custom webhook to call per repo would be a valuable step in this direction.

**Comment by programmdesign** [comment]
Which notifications do you mean? That the analysis of your project is finished?

**Comment by jakirkham** [comment]
Yes, that analysis of my project is finished.

**Comment by programmdesign** [comment]
We'll put this on our roadmap. Right now, this feature isn't available.
